name: fake_store_design
description: A modern e-commerce Flutter app providing a seamless shopping experience with product categories, cart, and user authentication.
version: 0.0.1
homepage: null

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  shimmer: ^3.0.0
  animate_do: ^4.2.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.4.1

dev_dependencies:
  mockito: ^5.4.2
  build_runner: ^2.4.7
  network_image_mock: ^2.1.1
  dart_code_linter: ^2.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


flutter:

  assets:
    - assets/test/
    - assets/config/app_config.json
    - assets/locale/en/semantics_json.json

  fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Regular.ttf

      - family: OpenSans
        fonts:
          - asset: assets/fonts/OpenSans-Light.ttf

      - family: Karla
        fonts:
          - asset: assets/fonts/Karla-Regular.ttf
