name: fake_store_design
description: A modern e-commerce Flutter app providing a seamless shopping experience with product categories, cart, and user authentication.
version: 0.0.1
homepage: null

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  animate_do: ^4.2.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


flutter:

  fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Regular.ttf

      - family: OpenSans
        fonts:
          - asset: assets/fonts/OpenSans-Light.ttf

      - family: Karla
        fonts:
          - asset: assets/fonts/Karla-Regular.ttf
